import { useEffect, useState } from 'react';
import { Alert, Platform, Share, StyleSheet, ScrollView, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { ScreenContainer, Header, Button } from '@/src/components';
import { useTheme } from '@/src/hooks/useTheme';
import { getPaymentWithBooking } from '@/src/services/payment';
import { formatCurrency, formatDate, formatTime } from '@/src/utils/pricing';
import { SPACING, FONT_SIZES } from '@/src/constants';
import type { Payment, Booking } from '@/src/types/database';

export default function TransactionHistoryDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { colors } = useTheme();
  const [payment, setPayment] = useState<Payment | null>(null);
  const [booking, setBooking] = useState<Booking | null>(null);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    if (!id) return;
    getPaymentWithBooking(id).then((data) => {
      setPayment(data as Payment | null);
      setBooking((data as any)?.bookings ?? null);
    });
  }, [id]);

  const buildReceiptText = () => {
    if (!payment) return '';
    return [
      'MBEvents Transaction Receipt',
      `Reference: ${payment.reference_number}`,
      `Amount: ${formatCurrency(Number(payment.amount))}`,
      `Status: ${payment.status}`,
      `Method: ${payment.method}`,
      `Date: ${new Date(payment.created_at).toLocaleDateString()}`,
      booking ? `Event: ${booking.event_types?.name ?? 'Event'}` : '',
      booking ? `Package: ${booking.packages?.name ?? 'Package'}` : '',
      booking ? `Date: ${formatDate(booking.event_date)}` : '',
      booking ? `Time: ${formatTime(booking.event_time)}` : '',
      booking?.event_address ? `Location: ${booking.event_address}` : '',
    ]
      .filter(Boolean)
      .join('\n');
  };

  const buildReceiptHtml = () => {
    if (!payment) return '';
    return `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <style>
            body { font-family: Arial, sans-serif; padding: 24px; color: #111; }
            .header { font-size: 24px; margin-bottom: 16px; font-weight: 700; }
            .section { margin-bottom: 12px; }
            .label { font-size: 12px; text-transform: uppercase; color: #666; margin-bottom: 4px; }
            .value { font-size: 16px; color: #111; }
            .row { display: flex; justify-content: space-between; margin-bottom: 8px; }
            .footer { margin-top: 24px; font-size: 12px; color: #888; }
          </style>
        </head>
        <body>
          <div class="header">MBEvents Transaction Receipt</div>
          <div class="section">
            <div class="row"><div class="label">Reference</div><div class="value">${payment.reference_number}</div></div>
            <div class="row"><div class="label">Amount</div><div class="value">${formatCurrency(Number(payment.amount))}</div></div>
            <div class="row"><div class="label">Status</div><div class="value">${payment.status}</div></div>
            <div class="row"><div class="label">Method</div><div class="value">${payment.method}</div></div>
            <div class="row"><div class="label">Date</div><div class="value">${new Date(payment.created_at).toLocaleDateString()}</div></div>
          </div>
          <div class="section">
            <div class="label">Booking Details</div>
            <div class="row"><div>Event</div><div>${booking?.event_types?.name ?? 'Event'}</div></div>
            <div class="row"><div>Package</div><div>${booking?.packages?.name ?? 'Package'}</div></div>
            <div class="row"><div>Date</div><div>${booking ? formatDate(booking.event_date) : '-'}</div></div>
            <div class="row"><div>Time</div><div>${booking ? formatTime(booking.event_time) : '-'}</div></div>
            <div class="row"><div>Location</div><div>${booking?.event_address ?? '-'}</div></div>
            <div class="row"><div>Total Booking</div><div>${booking ? formatCurrency(Number(booking.total)) : '-'}</div></div>
          </div>
          <div class="footer">Generated by MBEvents</div>
        </body>
      </html>
    `;
  };

  const saveAndShareReceipt = async (uri: string, mimeType: string) => {
    if (Platform.OS === 'web') {
      const link = document.createElement('a');
      link.href = uri;
      link.download = `MBEvents_receipt_${payment?.reference_number}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      return;
    }

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, {
        mimeType,
        dialogTitle: 'Share Receipt',
      });
    } else {
      await Share.share({ message: buildReceiptText() });
    }
  };

  const createPdfReceipt = async () => {
    const html = buildReceiptHtml();
    const { uri } = await Print.printToFileAsync({ html });

    if (Platform.OS === 'web') {
      return uri;
    }

    return uri;
  };

  const handleShareReceipt = async () => {
    if (!payment) return;

    try {
      const uri = await createPdfReceipt();
      await saveAndShareReceipt(uri, 'application/pdf');
    } catch (error: unknown) {
      Alert.alert('Share Error', (error as Error)?.message ?? 'Unable to share receipt.');
    }
  };

  const handleDownloadReceipt = async () => {
    if (!payment) return;
    setDownloading(true);

    try {
      const uri = await createPdfReceipt();

      if (Platform.OS === 'web') {
        return;
      }

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Download Receipt',
        });
      } else {
        Alert.alert('Download Ready', `Receipt is ready at ${uri}`);
      }
    } catch (error: unknown) {
      Alert.alert('Download Error', (error as Error)?.message ?? 'Unable to download receipt.');
    } finally {
      setDownloading(false);
    }
  };

  return (
    <ScreenContainer>
      <Header title="Transaction Detail" />
      {!payment ? (
        <View style={styles.emptyContainer}>
          <Text style={[styles.emptyText, { color: colors.text }]}>Transaction details could not be loaded.</Text>
        </View>
      ) : (
        <ScrollView contentContainerStyle={styles.content}>
          <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}> 
            <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>Reference</Text>
            <Text style={[styles.sectionValue, { color: colors.text }]}>{payment.reference_number}</Text>
            <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>Amount</Text>
            <Text style={[styles.sectionValue, { color: colors.primary }]}>{formatCurrency(Number(payment.amount))}</Text>
            <View style={styles.row}>
              <Text style={[styles.label, { color: colors.textSecondary }]}>Status</Text>
              <Text style={[styles.value, { color: payment.status === 'paid' ? colors.success ?? '#28a745' : colors.warning ?? '#f59e0b' }]}> 
                {payment.status}
              </Text>
            </View>
            <View style={styles.row}>
              <Text style={[styles.label, { color: colors.textSecondary }]}>Method</Text>
              <Text style={[styles.value, { color: colors.text }]}>{payment.method}</Text>
            </View>
            <View style={styles.row}>
              <Text style={[styles.label, { color: colors.textSecondary }]}>Date</Text>
              <Text style={[styles.value, { color: colors.text }]}>{new Date(payment.created_at).toLocaleDateString()}</Text>
            </View>
          </View>

          <View style={styles.buttonGroup}>
            <Button title="Share Receipt" onPress={handleShareReceipt} />
            <Button title="Download PDF" onPress={handleDownloadReceipt} loading={downloading} variant="secondary" />
          </View>

          {booking ? (
            <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}> 
              <Text style={[styles.cardTitle, { color: colors.text }]}>Booking Details</Text>
              <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>Event</Text>
              <Text style={[styles.sectionValue, { color: colors.text }]}>{booking.event_types?.name ?? 'Event'}</Text>
              <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>Package</Text>
              <Text style={[styles.sectionValue, { color: colors.text }]}>{booking.packages?.name ?? 'Package'}</Text>
              <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>Date</Text>
              <Text style={[styles.sectionValue, { color: colors.text }]}>{formatDate(booking.event_date)}</Text>
              <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>Time</Text>
              <Text style={[styles.sectionValue, { color: colors.text }]}>{formatTime(booking.event_time)}</Text>
              {booking.event_address && (
                <>
                  <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>Location</Text>
                  <Text style={[styles.sectionValue, { color: colors.text }]}>{booking.event_address}</Text>
                </>
              )}
              <View style={styles.row}>
                <Text style={[styles.label, { color: colors.textSecondary }]}>Total Booking</Text>
                <Text style={[styles.value, { color: colors.primary }]}>{formatCurrency(Number(booking.total))}</Text>
              </View>
            </View>
          ) : (
            <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}> 
              <Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>Booking details not available.</Text>
            </View>
          )}
        </ScrollView>
      )}
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  content: { paddingBottom: SPACING.xl },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: SPACING.lg },
  emptyText: { fontSize: FONT_SIZES.md, textAlign: 'center' },
  card: { borderRadius: 16, borderWidth: 1, padding: SPACING.lg, marginBottom: SPACING.lg },
  sectionLabel: { fontSize: FONT_SIZES.xs, textTransform: 'uppercase', marginTop: SPACING.sm },
  sectionValue: { fontSize: FONT_SIZES.md, fontWeight: '700', marginTop: SPACING.xs },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: SPACING.sm },
  label: { fontSize: FONT_SIZES.sm },
  value: { fontSize: FONT_SIZES.sm, fontWeight: '700' },
  buttonGroup: { flexDirection: 'row', gap: SPACING.sm, marginBottom: SPACING.lg },
  cardTitle: { fontSize: FONT_SIZES.lg, fontWeight: '700', marginBottom: SPACING.md },
});
